version: '3'

services:
  elasticsearch:
    image: elastic/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_HEAP_SIZE=1024m"
      - "discovery.type=single-node"
      - "ES_PROTOCOL=http"
      - "xpack.security.enabled=false"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY="MVE6Y9s8s0wuWokhCgeyHyqYA19FajbA"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  filebeat:
    image: elastic/filebeat:8.10.2
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs.log:/var/log/app_logs/logs.log
    depends_on:
      - kibana
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic