export const CREATE_USER_PROVIDER = 'CREATE_USER_PROVIDER';
export const LOGIN_USER_PROVIDER = 'LOGIN_USER_PROVIDER';
export const PROFILE_USER_PROVIDER = 'PROFILE_USER_PROVIDER';

export const SESSION_USER_PROVIDER = 'SESSION_USER_PROVIDER';

export const LOGOUT_USER_PROVIDER = 'LOGOUT_USER_PROVIDER';
